accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.forms import ClientLoginForm
from . import views

app_name = 'accounts'
urlpatterns = [
    path('cliente/signup/', views.cliente_signup, name='cliente_signup'),
    path('cliente/login/', views.cliente_login, name='cliente_login'),
    path('equipe/login/', views.equipe_login, name='equipe_login'),
]

api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cardapio/', views.ItemList.as_view()),
    path('cardapio/<int:pk>/', views.ItemDetail.as_view()),
    path('pedidos/', views.PedidoList.as_view()),
    path('pedidos/<int:pk>/', views.PedidoDetail.as_view()),
    path('mesas/', views.MesaList.as_view()),
    path('mesas/<int:pk>/', views.MesaDetail.as_view()),
    path('contas/', views.ContaList.as_view()),
    path('contas/<int:pk>/', views.ContaDetail.as_view()),
    path('clientes/', views.ClienteList.as_view()),
    path('clientes/<int:pk>/', views.ClienteDetail.as_view()),
    path('gerentes/', views.GerenteList.as_view()),
    path('gerentes/<int:pk>/', views.GerenteDetail.as_view()),
    path('garcons/', views.GarcomList.as_view()),
    path('garcons/<int:pk>/', views.GarcomDetail.as_view()),
    path('chefcozinhas/', views.ChefCozinhaList.as_view()),
    path('chefcozinhas/<int:pk>/', views.ChefCozinhaDetail.as_view()),
]

garfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pedidos.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls'))
]

pedidos/urls.py
from django.urls import path

from . import views

app_name = 'pedidos'
urlpatterns = [
    path('', views.index, name='index'),
    path('pedidos/', views.list_pedidos, name='pedidos'),
    path('cardapio/', views.cardapio, name='cardapio'),
    path('cardapio/<int:item_id>/pedir/', views.fazer_pedido, name='fazer_pedido'),
    path('cardapio/create/', views.create_item, name='create_item'),
    path('cardapio/<int:item_id>/update/', views.update_item, name='update_item'),
    path('contas/', views.list_contas, name='list_contas'),
    path('contas/pedir/', views.pedir_conta, name='pedir_conta'),
    path('contas/<int:conta_id>/pagar/', views.pagar_conta, name='pagar_conta'),
    path('mesas/', views.list_mesas, name='list_mesas'),
    path('mesas/<int:mesa_id>/', views.detail_mesa, name='detail_mesa'),
    path('mesas/create/', views.create_mesa, name='create_mesa'),
    path('mesas/<int:mesa_id>/update/', views.update_mesa, name='update_mesa'),
]

pedidos/models.py
from django.db import models

from accounts.models import ChefCozinha, Cliente, Garcom


class Mesa(models.Model):
    capacidade = models.IntegerField(verbose_name="Capacidade")
    localizacao = models.CharField(max_length=255, verbose_name="Localização")
    disponivel = models.BooleanField(verbose_name="Disponível")

    def __str__(self):
        return f"Mesa {self.id}"

class Item(models.Model):
    """Item do cardápio"""
    nome = models.CharField(max_length=255, verbose_name="Nome")
    preco = models.FloatField(verbose_name="Preço")
    descricao = models.CharField(max_length=255, verbose_name="Descrição")
    foto_url = models.URLField(max_length=255, verbose_name="URL da foto")
    disponivel = models.BooleanField(verbose_name="Disponível")

    def __str__(self):
        return f"{self.nome}"

class Conta(models.Model):
    pago = models.BooleanField(verbose_name="Pago")

    def __str__(self):
        return f"Conta {self.id}"

class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Cliente")
    
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name="Item")
    observacoes = models.CharField(max_length=255, blank=True, default="", verbose_name="Observações")

    time_realizado = models.DateTimeField() # quando o pedido foi realizado pelo cliente
    
    chefcozinha = models.ForeignKey(ChefCozinha, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Chef de Cozinha")
    time_preparando = models.DateTimeField(blank=True, null=True) # quando o pedido começou a ser preparado pelo chef de cozinha
    
    time_pronto = models.DateTimeField(blank=True, null=True) # quando o pedido ficou pronto

    garcom = models.ForeignKey(Garcom, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Garçom")
    time_entregue = models.DateTimeField(blank=True, null=True) # quando o pedido foi entregue ao cliente

    conta = models.ForeignKey(Conta, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Conta")

    class Meta:
        permissions = [
            ("preparar_pedido", "Can preparar pedido"),
            ("entregar_pedido", "Can entregar pedido"),
        ]

    def __str__(self):
        return f"{self.item}, para {self.cliente}"

pedidos/forms.py
from django import forms
from .models import Item, Mesa, Pedido


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'nome',
            'preco',
            'descricao',
            'foto_url',
            'disponivel',
        ]
        labels = {
            'nome': 'Nome',
            'preco': 'Preço',
            'descricao': 'Descrição',
            'foto_url': 'URL da foto',
            'disponivel': 'Disponível',
        }

class MesaForm(forms.ModelForm):
    class Meta:
        model = Mesa
        fields = [
            'capacidade',
            'localizacao',
            'disponivel',
        ]
        labels = {
            'capacidade': 'Capacidade',
            'localizacao': 'Localização',
            'disponivel': 'Disponível',
        }

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = [
            'observacoes',
        ]
        labels = {
            'observacoes': 'Observações',
        }

pedidos/views.py
from django.contrib.auth import login
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.contrib.auth.decorators import login_required, permission_required
from django.template.defaulttags import register

from pedidos.forms import ItemForm, MesaForm, PedidoForm
from .models import Conta, Mesa, Pedido, Item


def index(request):
    if request.user.is_authenticated:
        try:
            request.user.cliente
            return HttpResponseRedirect(reverse('pedidos:cardapio'))
        except:
            pass
        try:
            garcom = request.user.garcom
            context = {'garcom': garcom}
            return render(request, 'pedidos/garcom.html', context)
        except ObjectDoesNotExist:
            pass
        try:
            chefcozinha = request.user.chefcozinha
            context = {'chefcozinha': chefcozinha}
            return render(request, 'pedidos/chefcozinha.html', context)
        except ObjectDoesNotExist:
            pass
        try:
            gerente = request.user.gerente
            context = {'gerente': gerente}
            return render(request, 'pedidos/gerente.html', context)
        except ObjectDoesNotExist:
            pass
    context = {}
    return render(request,'pedidos/index.html', context)

def cardapio(request):
    item_list = Item.objects.filter(disponivel=True)
    item_indisp = Item.objects.filter(disponivel=False)
    context = {'item_list': item_list, 'item_indisp': item_indisp}
    
    if request.user.is_authenticated:
        context['pode_pedir'] = True
        try:
            cliente = request.user.cliente
            for conta in Conta.objects.filter(pago=False):
                if conta.pedido_set.all()[0].cliente == cliente:
                    context['conta'] = conta
                    context['total'] = 0
                    for pedido in conta.pedido_set.all():
                        context['total'] += pedido.item.preco
                    context['pode_pedir'] = False
            if context['pode_pedir']:
                context['pedidos'] = Pedido.objects.filter(cliente=cliente).filter(conta=None)
                context['total'] = 0
                for pedido in context['pedidos']:
                    context['total'] += pedido.item.preco
        except ObjectDoesNotExist:
            context['pode_pedir'] = False
    else:
        context['pode_pedir'] = False

    return render(request, 'pedidos/cardapio.html', context)

@login_required
@permission_required('pedidos.add_item')
def create_item(request):
    if request.method == 'POST':
        item_form = ItemForm(request.POST)
        if item_form.is_valid():
            item = Item(**item_form.cleaned_data)
            item.save()
    return HttpResponseRedirect(reverse('pedidos:cardapio'))


@login_required
@permission_required('pedidos.add_pedido')
def fazer_pedido(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    if request.method == 'POST':
        pedido_form = PedidoForm(request.POST)
        if pedido_form.is_valid():
            for _ in range(int(request.POST['quantidade'])):
                pedido = Pedido(
                    cliente=request.user.cliente,
                    item=item,
                    observacoes=pedido_form.cleaned_data['observacoes'],
                    time_realizado=timezone.localtime(timezone.now()),
                )
                pedido.save()
    return HttpResponseRedirect(reverse('pedidos:cardapio'))

@login_required
@permission_required('pedidos.change_item')
def update_item(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    if request.method == 'POST':
        item_form = ItemForm(request.POST)
        if item_form.is_valid():
            item.nome = item_form.cleaned_data['nome']
            item.preco = item_form.cleaned_data['preco']
            item.descricao = item_form.cleaned_data['descricao']
            item.foto_url = item_form.cleaned_data['foto_url']
            item.disponivel = item_form.cleaned_data['disponivel']
            item.save()
    return HttpResponseRedirect(reverse('pedidos:cardapio'))

@login_required
@permission_required('pedidos.view_pedido')
def list_pedidos(request):
    if request.method == 'POST':
        if 'preparando' in request.POST and request.user.has_perm('pedidos.preparar_pedido'):
            pedido_id = request.POST['pedido_id']
            pedido = Pedido.objects.get(pk=pedido_id)
            try:
                chefcozinha = request.user.chefcozinha
                pedido.chefcozinha = chefcozinha
                pedido.time_preparando = timezone.localtime(timezone.now())
                pedido.save()
            except ObjectDoesNotExist:
                pass
        if 'pronto' in request.POST and request.user.has_perm('pedidos.preparar_pedido'):
            pedido_id = request.POST['pedido_id']
            pedido = Pedido.objects.get(pk=pedido_id)
            try:
                pedido.time_pronto = timezone.localtime(timezone.now())
                pedido.save()
            except ObjectDoesNotExist:
                pass
        if 'entregue' in request.POST and request.user.has_perm('pedidos.entregar_pedido'):
            pedido_id = request.POST['pedido_id']
            pedido = Pedido.objects.get(pk=pedido_id)
            try:
                garcom = request.user.garcom
                pedido.garcom = garcom
                pedido.time_entregue = timezone.localtime(timezone.now())
                pedido.save()
            except ObjectDoesNotExist:
                pass
        return HttpResponseRedirect(reverse('pedidos:pedidos'))
    
    pedidos_realizados = Pedido.objects.filter(time_preparando=None)
    pedidos_preparacao = Pedido.objects.filter(time_pronto=None).exclude(time_preparando=None)
    pedidos_prontos = Pedido.objects.filter(time_entregue=None).exclude(time_preparando=None).exclude(time_pronto=None)
    context = {
        'pedidos_realizados': pedidos_realizados,
        'pedidos_preparacao': pedidos_preparacao,
        'pedidos_prontos': pedidos_prontos,
    }
    return render(request, 'pedidos/pedidos.html', context)

@login_required
@permission_required('pedidos.add_conta')
def pedir_conta(request):
    if request.method == 'POST':
        cliente = request.user.cliente
        pedidos = Pedido.objects.filter(cliente=cliente).filter(conta=None)
        if pedidos:
            conta = Conta(pago=False)
            conta.save()
            for pedido in pedidos:
                pedido.conta = conta
                pedido.save()
    return HttpResponseRedirect(reverse('pedidos:cardapio'))

@login_required
@permission_required('pedidos.change_conta')
def pagar_conta(request, conta_id):
    if request.method == 'POST':
        conta = get_object_or_404(Conta, pk=conta_id)
        conta.pago = True
        conta.save()
    return HttpResponseRedirect(reverse('pedidos:list_contas'))

@login_required
@permission_required('pedidos.view_conta')
def list_contas(request):
    contas = Conta.objects.filter(pago=False)
    totais = {}
    for conta in contas:
        totais[conta.id] = 0
        for pedido in conta.pedido_set.all():
            totais[conta.id] += pedido.item.preco
    context = {'contas': contas, 'totais': totais}
    return render(request, 'pedidos/list_contas.html', context)

@login_required
@permission_required('pedidos.view_mesa')
def list_mesas(request):
    mesas_disp = Mesa.objects.filter(disponivel=True)
    mesas_indisp = Mesa.objects.filter(disponivel=False)
    context = {'mesas_disp': mesas_disp, 'mesas_indisp': mesas_indisp}
    return render(request, 'pedidos/list_mesas.html', context)

@login_required
@permission_required('pedidos.view_mesa')
def detail_mesa(request, mesa_id):
    mesa = get_object_or_404(Mesa, pk=mesa_id)
    context = {'mesa': mesa}
    return render(request, 'pedidos/detail_mesa.html', context)

@login_required
@permission_required('pedidos.add_mesa')
def create_mesa(request):
    if request.method == 'POST':
        mesa_form = MesaForm(request.POST)
        if mesa_form.is_valid():
            mesa = Mesa(**mesa_form.cleaned_data)
            mesa.save()
    return HttpResponseRedirect(
        reverse('pedidos:list_mesas')
    )

@login_required
@permission_required('pedidos.change_mesa')
def update_mesa(request, mesa_id):
    mesa = get_object_or_404(Mesa, pk=mesa_id)
    if request.method == 'POST':
        mesa_form = MesaForm(request.POST)
        if mesa_form.is_valid():
            mesa.capacidade = mesa_form.cleaned_data['capacidade']
            mesa.localizacao = mesa_form.cleaned_data['localizacao']
            mesa.disponivel = mesa_form.cleaned_data['disponivel']
            mesa.save()
    return HttpResponseRedirect(
        reverse('pedidos:list_mesas')
    )


@register.filter
def get_item(dict, key):
    return dict.get(key)

pedidos/templates/pedidos/cardapio.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
GARFO
{% endblock title %}

{% block content %}

<header id="centered-header">
    {% if user.is_authenticated %}
        {% if user.cliente %}
            <div id="bill-button" style="cursor:pointer;" onclick="document.getElementById('modal-conta').style.display='block'"><img src="{% static 'bill_purple.svg' %}"></div>
        {% else %}
            <a id="return-button" href="{% url 'pedidos:index' %}"><img src="{% static 'arrow_back.svg' %}"></a>
        {% endif %}
    {% endif %}
    <div id="img-container-2"><img src="{% static 'logo.svg' %}"></div>
    {% if user.is_authenticated %}
        <a id="exit-button" href="{% url 'logout' %}"><img src="{% static 'exit.svg' %}"></a>
    {% endif %}
  </header>
  
  <main id="container-central">
      <!-- Modal da conta -->
    <div id="modal-conta" class="background">
        <div class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <p style="cursor:pointer;" onclick="document.getElementById('modal-conta').style.display='none'" class="close-button">&times</p>
                </div>
                <div class="modal-body">
                    {% if pode_pedir %}
                        <p class="modal-title-conta">Pedidos feitos:</p>
                        {% if pedidos %}
                            <ul>
                                {% for pedido in pedidos %}
                                    <li>{{ pedido.item.nome }}: R${{ pedido.item.preco|floatformat:2 }}</li>
                                {% endfor %}
                            </ul>
                            <p class="item-price">Total: R${{ total|floatformat:2 }}</p>
                        {% else %}
                            <p class="modal-text">Você não pediu nada ainda</p>
                        {% endif %}
                        <form method="POST" action="{% url 'pedidos:pedir_conta' %}">
                            {% csrf_token %}
                            <button type="submit">Pedir Conta</button>
                        </form>
                    {% endif %}

                    {% if conta %}
                        <p class="modal-title-conta">Conta aberta:</p>
                        <ul>
                            {% for pedido in conta.pedido_set.all %}
                                <li>{{ pedido.item.nome }}: R${{ pedido.item.preco|floatformat:2 }}</li>
                            {% endfor %}
                        </ul>
                        
                        <p class="item-price">Total: R${{ total|floatformat:2 }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <span>CARDÁPIO</span>
    <section id="container-inner-2">
        {% if item_list %}
            {% for item in item_list %}
            <div style="cursor:pointer;" onclick="document.getElementById('modal-item-{{ item.id }}').style.display='block'" class="card img-card" id="single-card">
                <div class="left-part">
                    <img id="item-img" src="{{ item.foto_url }}">
                </div>

                <div class="right-part">
                    <div id="item-name">{{ item.nome }}</div>
                </div>
            </div>

            <!-- Modal -->
            <div id="modal-item-{{ item.id }}" class="background">
                <div class="modal">
                    <div class="modal-content">
                        <div class="modal-header">
                            <p style="cursor:pointer;" onclick="document.getElementById('modal-item-{{ item.id }}').style.display='none'" class="close-button">&times</p>
                        </div>
                        <div class="modal-body">
                            <div class="modal-img-container">
                                <img src="{{ item.foto_url }}" alt="{{ item.nome }}">
                            </div> 
                            <p class="modal-title">{{ item.nome }}</p>
                            {% if user.cliente %}
                                <p class="modal-text">{{ item.descricao }}</p>
                                <p class="modal-text item-price">Preço: R${{ item.preco|floatformat:2 }}</p>
                                {% if pode_pedir %}
                                    <form method="POST" action="{% url 'pedidos:fazer_pedido' item.id %}">
                                        {% csrf_token %}
                                        <div>
                                            <label for="observacoes">Observações: </label>
                                            <input type="text" name="observacoes" id="observacoes">
                                        </div>
                                        <div id="div-qtde-pedir">
                                            <div id="div-quantidade">
                                                <label for="quantidade">QTDE:</label>
                                                <input type="number" step="1" name="quantidade" id="quantidade" value="1">
                                            </div>
                                            <button type="submit">PEDIR</button>
                                        </div>
                                    </form>
                                {% endif %}
                            {% endif %}

                            {% if user.gerente %}
                                <form method="POST" action="{% url 'pedidos:update_item' item.id %}">
                                    {% csrf_token %}
                                    <div>
                                        <label for="id_nome">Nome: </label>
                                        <input type="text" name="nome" required id="id_nome" value="{{ item.nome }}">
                                    </div>

                                    <div>
                                        <label for="id_preco">Preço: </label>
                                        <input type="number" step="any" name="preco" required id="id_preco" value='{{ item.preco|stringformat:".2f" }}'>
                                    </div>

                                    <div>
                                        <label for="id_descricao">Descrição: </label>
                                        <input type="text" name="descricao" required id="id_descricao" value="{{ item.descricao }}">
                                    </div>

                                    <div>
                                        <label for="id_foto_url">URL da foto: </label>
                                        <input type="url" name="foto_url" required id="id_foto_url" value="{{ item.foto_url }}"
                                            maxlength="255">
                                    </div>

                                    <div>
                                        <label for="id_disponivel">Disponível: </label>
                                        <input type="checkbox" name="disponivel" id="id_disponivel" {% if item.disponivel %} checked {% endif %}>
                                    </div>

                                    <button type="submit">ATUALIZAR</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% endif %}

        {% if user.gerente %}
        <div style="cursor:pointer;" onclick="document.getElementById('modal-add-item').style.display='block'" class="card" id="add-card">
            <img src="{% static 'plus.svg' %}">
        </div>

        <!-- Modal adicionar item -->
        <div id="modal-add-item" class="background">
            <div class="modal">
                <div class="modal-content">
                    <div class="modal-header">
                        <p style="cursor:pointer;" onclick="document.getElementById('modal-add-item').style.display='none'" class="close-button">&times</p>
                    </div>
                    <div class="modal-body">
                        <p class="modal-title modal-title-mesa">Novo item</p>

                        <form method="POST" action="{% url 'pedidos:create_item' %}">
                            {% csrf_token %}
                            <div>
                                <label for="id_nome">Nome: </label>
                                <input type="text" name="nome" required id="id_nome" value="{{ item.nome }}">
                            </div>

                            <div>
                                <label for="id_preco">Preço: </label>
                                <input type="number" step="any" name="preco" required id="id_preco" value='{{ item.preco|stringformat:".2f" }}'>
                            </div>

                            <div>
                                <label for="id_descricao">Descrição: </label>
                                <input type="text" name="descricao" required id="id_descricao" value="{{ item.descricao }}">
                            </div>

                            <div>
                                <label for="id_foto_url">URL da foto: </label>
                                <input type="url" name="foto_url" required id="id_foto_url" value="{{ item.foto_url }}"
                                    maxlength="255">
                            </div>

                            <div>
                                <label for="id_disponivel">Disponível: </label>
                                <input type="checkbox" name="disponivel" id="id_disponivel" {% if item.disponivel %} checked {% endif %}>
                            </div>

                            <button type="submit">CRIAR</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {% endif %}

    </section>

    {% if user.gerente %}
        {% if item_indisp %}
        <h3>ITENS INDISPONÍVEIS</h3>
        <section id="container-inner-2">
            {% for item in item_indisp %}
                <div style="cursor:pointer;" onclick="document.getElementById('modal-item-{{ item.id }}').style.display='block'" class="card img-card" id="single-card">
                    <div class="left-part">
                        <img id="item-img" src="{{ item.foto_url }}">
                    </div>

                    <div class="right-part">
                        <div id="item-name">{{ item.nome }}</div>
                    </div>
                </div>

                <!-- Modal -->
                <div id="modal-item-{{ item.id }}" class="background">
                    <div class="modal">
                        <div class="modal-content">
                            <div class="modal-header">
                                <p style="cursor:pointer;" onclick="document.getElementById('modal-item-{{ item.id }}').style.display='none'" class="close-button">&times</p>
                            </div>
                            <div class="modal-body">
                                <div class="modal-img-container">
                                    <img src="{{ item.foto_url }}" alt="{{ item.nome }}">
                                </div>
                                <p class="modal-title">{{ item.nome }}</p>
                                <form method="POST" action="{% url 'pedidos:update_item' item.id %}">
                                    {% csrf_token %}
                                    <div>
                                        <label for="id_nome">Nome: </label>
                                        <input type="text" name="nome" required id="id_nome" value="{{ item.nome }}">
                                    </div>

                                    <div>
                                        <label for="id_preco">Preço: </label>
                                        <input type="number" step="any" name="preco" required id="id_preco" value='{{ item.preco|stringformat:".2f" }}'>
                                    </div>

                                    <div>
                                        <label for="id_descricao">Descrição: </label>
                                        <input type="text" name="descricao" required id="id_descricao" value="{{ item.descricao }}">
                                    </div>

                                    <div>
                                        <label for="id_foto_url">URL da foto: </label>
                                        <input type="url" name="foto_url" required id="id_foto_url" value="{{ item.foto_url }}" maxlength="255">
                                    </div>

                                    <div>
                                        <label for="id_disponivel">Disponível: </label>
                                        <input type="checkbox" name="disponivel" id="id_disponivel" {% if item.disponivel %} checked {% endif %} >
                                    </div>

                                    <button type="submit">ATUALIZAR</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </section>
        {% endif %}
    {% endif %}
  </main>
  
  {% endblock content %}

pedidos/templates/pedidos/chefcozinha.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Chef de Cozinha | GARFO
{% endblock title %}

{% block content %}

<header id="cabecalho-principal">
    <a id="exit-button" href="{% url 'logout' %}"><img src="{% static 'exit.svg' %}"></a>
</header>


<main id="container-principal">
    
    <div id="img-container"><img src="{% static 'logo.svg' %}"></div> 
    
    <h1>{{ user }}</h1>
    
    <div id="button-container">
    <a href="{% url 'pedidos:pedidos' %}"> 
            <button>
                <img src="{% static 'list.svg' %}">
                <br>
                PEDIDOS
            </button>
        </a>
    </div>
</main>

{% endblock content %}

pedidos/templates/pedidos/delete_item.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
GARFO
{% endblock title %}

{% block content %}

<form method="POST" action="{% url 'pedidos:delete_item' item.id %}">
    {% csrf_token %}
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

pedidos/templates/pedidos/garcom.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Garçom | GARFO
{% endblock title %}

{% block content %}

<header id="cabecalho-principal">
    <a id="exit-button" href="{% url 'logout' %}"><img src="{% static 'exit.svg' %}"></a>
</header>

<main id="container-principal">

    <div id="img-container"><img src="{% static 'logo.svg' %}"></div> 

    <h1>{{ user }}</h1>

    <div id="button-container">
        <a href="{% url 'pedidos:pedidos' %}"> 
            <button>
                <img src="{% static 'list.svg' %}">
                <br>
                PEDIDOS
            </button>
        </a>

        <a href="{% url 'pedidos:list_contas' %}"> 
            <button>
                <img src="{% static 'bill_white.svg' %}">
                <br>
                CONTAS
            </button>
        </a>
    </div>  

</main>

{% endblock content %}

pedidos/templates/pedidos/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
GARFO
{% endblock title %}

{% block content %}

<header id="cabecalho-index">
    <a href="{% url 'accounts:equipe_login' %}">EQUIPE</a>
</header>

<main id="container-principal">
    <div id="img-container"><img src="{% static 'logo.svg' %}"></div> 

    <a href="{% url 'accounts:cliente_login' %}"> 
        <button>FAZER PEDIDO</button>
    </a>
</main>

{% endblock content %}