accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.forms import ClientLoginForm
from . import views

app_name = 'accounts'
urlpatterns = [
    path('cliente/signup/', views.cliente_signup, name='cliente_signup'),
    path('cliente/login/', views.cliente_login, name='cliente_login'),
    path('equipe/login/', views.equipe_login, name='equipe_login'),
]

api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cardapio/', views.ItemList.as_view()),
    path('cardapio/<int:pk>/', views.ItemDetail.as_view()),
    path('pedidos/', views.PedidoList.as_view()),
    path('pedidos/<int:pk>/', views.PedidoDetail.as_view()),
    path('mesas/', views.MesaList.as_view()),
    path('mesas/<int:pk>/', views.MesaDetail.as_view()),
    path('contas/', views.ContaList.as_view()),
    path('contas/<int:pk>/', views.ContaDetail.as_view()),
    path('clientes/', views.ClienteList.as_view()),
    path('clientes/<int:pk>/', views.ClienteDetail.as_view()),
    path('gerentes/', views.GerenteList.as_view()),
    path('gerentes/<int:pk>/', views.GerenteDetail.as_view()),
    path('garcons/', views.GarcomList.as_view()),
    path('garcons/<int:pk>/', views.GarcomDetail.as_view()),
    path('chefcozinhas/', views.ChefCozinhaList.as_view()),
    path('chefcozinhas/<int:pk>/', views.ChefCozinhaDetail.as_view()),
]

garfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pedidos.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls'))
]

pedidos/urls.py
from django.urls import path

from . import views

app_name = 'pedidos'
urlpatterns = [
    path('', views.index, name='index'),
    path('pedidos/', views.list_pedidos, name='pedidos'),
    path('cardapio/', views.cardapio, name='cardapio'),
    path('cardapio/<int:item_id>/pedir/', views.fazer_pedido, name='fazer_pedido'),
    path('cardapio/create/', views.create_item, name='create_item'),
    path('cardapio/<int:item_id>/update/', views.update_item, name='update_item'),
    path('contas/', views.list_contas, name='list_contas'),
    path('contas/pedir/', views.pedir_conta, name='pedir_conta'),
    path('contas/<int:conta_id>/pagar/', views.pagar_conta, name='pagar_conta'),
    path('mesas/', views.list_mesas, name='list_mesas'),
    path('mesas/<int:mesa_id>/', views.detail_mesa, name='detail_mesa'),
    path('mesas/create/', views.create_mesa, name='create_mesa'),
    path('mesas/<int:mesa_id>/update/', views.update_mesa, name='update_mesa'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save
from cpf_field.models import CPFField
from django.contrib.auth.models import Group, Permission


class Cliente(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Usuário"
    )
    cpf = CPFField(verbose_name="CPF")
    mesa = models.ForeignKey("pedidos.Mesa", on_delete=models.CASCADE, verbose_name="Mesa")

    def __str__(self):
        return self.user.__str__()

class Gerente(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Usuário"
    )

    def __str__(self):
        return self.user.__str__()

class Garcom(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Usuário"
    )

    def __str__(self):
        return self.user.__str__()

class ChefCozinha(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Usuário"
    )

    def __str__(self):
        return self.user.__str__()


PERMISSIONS = {
    'Gerente': {
        'Mesa': ['add', 'change', 'view'],
        'Item': ['add', 'change', 'view'],
        'Conta': ['view'],
        'Pedido': ['view'],
    },
    'Garcom': {
        'Conta': ['change', 'view'],
        'Item': ['view'],
        'Mesa': ['view'],
        'Pedido': ['entregar', 'view'],
    },
    'ChefCozinha': {
        'Item': ['view'],
        'Mesa': ['view'],
        'Pedido': ['preparar', 'view'],        
    },
    'Cliente': {
        'Conta': ['add'],
        'Item': ['view'],
        'Mesa': ['view'],
        'Pedido': ['add'],
    },
}

@receiver(post_save, sender=Gerente)
@receiver(post_save, sender=Garcom)
@receiver(post_save, sender=ChefCozinha)
@receiver(post_save, sender=Cliente)
def update_permissions(sender, instance, created, **kwargs):
    group_name = sender.__name__
    group, created = Group.objects.get_or_create(name=group_name)
    for model_name in PERMISSIONS[group_name]:
        for permission_name in PERMISSIONS[group_name][model_name]:
            name = f"Can {permission_name} {model_name.lower()}"
            try:
                permission = Permission.objects.get(name=name)
            except:
                print("Permissão não encontrada")
                print(permission_name)
                continue
            group.permissions.add(permission)
    group.user_set.add(instance.user)
    group.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django.forms import fields
from cpf_field.models import MyModel
from cpf_field.validators import validate_cpf

from accounts.models import Cliente, Gerente, Garcom, ChefCozinha
from pedidos.models import Mesa


class ClientLoginForm(AuthenticationForm):
   def __init__(self, * args, ** kwargs): super(ClientLoginForm, self).__init__( * args, ** kwargs)

   username = forms.CharField(widget=forms.TextInput(
      attrs = {
         'class': 'form-control',
         'placeholder': 'Nome',
      }))
   password = forms.CharField(widget=forms.PasswordInput(
      attrs = {
         'class': 'form-control',
         'placeholder': 'Senha',
      }))
   mesa = forms.ModelChoiceField(queryset=Mesa.objects.filter(disponivel=True), empty_label="Escolha uma mesa")

class ClienteCreationForm(UserCreationForm):
   def __init__(self, * args, ** kwargs): super(UserCreationForm, self).__init__( * args, ** kwargs)

   username = forms.CharField(widget=forms.TextInput(
      attrs = {
         'class': 'form-control',
         'placeholder': 'Nome',
      }))
   cpf = MyModel._meta.get_field('cpf').formfield(
      widget=forms.NumberInput(
         attrs = {
            'class': 'form-control',
            'placeholder': 'CPF',
         }
      ),
      validators=[validate_cpf]
   )
   password1 = forms.CharField(widget=forms.PasswordInput(
      attrs = {
         'class': 'form-control',
         'placeholder': 'Senha',
      }))
   password2 = forms.CharField(widget=forms.PasswordInput(
      attrs = {
         'class': 'form-control',
         'placeholder': 'Repita a senha',
      }))
   mesa = forms.ModelChoiceField(queryset=Mesa.objects.filter(disponivel=True), empty_label="Escolha uma mesa")

   field_order = ['username', 'cpf', 'password1', 'password2', 'mesa']

accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.core.exceptions import ValidationError

from accounts.forms import ClienteCreationForm, ClientLoginForm
from accounts.models import Cliente

def cliente_signup(request):
    if request.method == 'POST':
        form = ClienteCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )
            cpf = form.cleaned_data['cpf']
            mesa = form.cleaned_data['mesa']
            cliente = Cliente(user=user, cpf=cpf, mesa=mesa)
            cliente.save()
            login(request, user)
            return HttpResponseRedirect(reverse('pedidos:index'))
    else:
        form = ClienteCreationForm()

    context = {'form': form}
    return render(request, 'accounts/cliente_signup.html', context)

def cliente_login(request):
    if request.method == 'POST':
        form = ClientLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            try:
                cliente = user.cliente
                cliente.mesa = form.cleaned_data['mesa']
                cliente.save()
                login(request, form.get_user())
                if request.POST['next']:
                    return HttpResponseRedirect(request.POST['next'])
                return HttpResponseRedirect(reverse('pedidos:index'))
            except:
                form.add_error("username", "Usuário não é um Cliente. Favor entrar pelo login da Equipe.")
    else:
        form = ClientLoginForm()

    context = {'form': form}
    return render(request, 'accounts/cliente_login.html', context)

def equipe_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            try:
                user.cliente
                form.add_error("username", "Usuário não faz parte da Equipe. Favor entrar pelo login de Cliente.")
            except:
                login(request, form.get_user()) 
                if request.POST['next']:
                    return HttpResponseRedirect(request.POST['next'])
                return HttpResponseRedirect(reverse('pedidos:index'))
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/equipe_login.html', context)

accounts/templates/accounts/client_login.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
Entrar
{% endblock title %}

{% block content %}
<header id="centered-header"> 
    <a id="return-button" href="{% url 'pedidos:index' %}"><img src="{% static 'arrow_back.svg' %}"></a> 
    <div id="img-container-2"><img src="{% static 'logo.svg' %}"></div> 
    <div id="no-img"></div>
</header>
<main id="container-central">
    <h1>ENTRAR</h1>

    <form method="post" action="{% url 'accounts:client_login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        
        {% if form.errors %}
        <p class="errortext">Sua senha e nome de usuário não correspondem. Tente novamente.</p>
        {% endif %}

        {% if next %}
        {% if user.is_authenticated %}
        <p class="errortext">Sua conta não possui acesso a esta página. Para prosseguir, faça um login com uma conta que tenha.</p>
        {% else %}
        <p class="errortext">Faça o login para ver esta página.</p>
        {% endif %}
        {% endif %}
        <button id="button" type="submit" value="login">Entrar</button>
        <input type="hidden" name="next" value="{{ next }}">
    </form>

    <p> Não tem uma conta? <a href="{% url 'accounts:client_signup_user' %}">Cadastre-se!</a></p>
</main>
{% endblock %}

accounts/templates/accounts/client_signup_user.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
Cadastrar
{% endblock title %}

{% block content %}
<header id="centered-header"> 
    <a id="return-button" href="{% url 'pedidos:index' %}"><img src="{% static 'arrow_back.svg' %}"></a> 
    <div id="img-container-2"><img src="{% static 'logo.svg' %}"></div> 
    <div id="no-img"></div>
</header>

<main id="container-central">
    <h1>CADASTRAR</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'accounts:client_signup' %}"><button type="submit">Continuar</button></a>
    </form>

    <p> Já tem uma conta? <a href="{% url 'accounts:client_login' %}">Entrar.</a></p>
</main>
{% endblock %}

accounts/templates/accounts/cliente_login.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
Entrar | GARFO
{% endblock title %}

{% block content %}
<header id="centered-header"> 
    <a id="return-button" href="{% url 'pedidos:index' %}"><img src="{% static 'arrow_back.svg' %}"></a> 
    <div id="img-container-2"><img src="{% static 'logo.svg' %}"></div> 
    <div id="no-img"></div>
</header>
<main id="container-central">
    <h1>ENTRAR</h1>

    
    <form method="post" action="{% url 'accounts:cliente_login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        
        <br>
        
        {% if form.errors %}
            {% for field in form.errors %}
                {% for error in form.errors|get_item:field %}
                    <p class="errortext">{{ error }}</p>
                {% endfor %}
            {% endfor %}
        {% endif %}
        
        {% if next %}
        {% if user.is_authenticated %}
        <p class="errortext">Sua conta não possui acesso a esta página. Para prosseguir, faça um login com uma conta que tenha.</p>
        {% else %}
        <p class="errortext">Faça o login para ver esta página.</p>
        {% endif %}
        {% endif %}
        <button id="button" type="submit" value="login">Entrar</button>
        <input type="hidden" name="next" value="{{ next }}">
    </form>
    
    <p> Não tem uma conta? <a href="{% url 'accounts:cliente_signup' %}">Cadastre-se!</a></p>
</main>
{% endblock %}

accounts/templates/accounts/cliente_signup.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
Cadastrar | GARFO
{% endblock title %}

{% block content %}
<header id="centered-header"> 
    <a id="return-button" href="{% url 'pedidos:index' %}"><img src="{% static 'arrow_back.svg' %}"></a> 
    <div id="img-container-2"><img src="{% static 'logo.svg' %}"></div> 
    <div id="no-img"></div>
</header>

<main id="container-central" action="{% url 'accounts:cliente_signup' %}">
    <h1>CADASTRAR</h1>

    
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <br>
        
        {% if form.errors %}
            {% for field in form.errors %}
                {% for error in form.errors|get_item:field %}
                    <p class="errortext">{{ error }}</p>
                {% endfor %}
            {% endfor %}
        {% endif %}
        
        <button type="submit">Cadastre-se</button>
    </form>

    <p> Já tem uma conta? <a href="{% url 'accounts:cliente_login' %}">Entrar.</a></p>
</main>
{% endblock %}

accounts/templates/accounts/equipe_login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
GARFO
{% endblock title %}

{% block content %}

<header id="cabecalho-principal">
    <a href="{% url 'pedidos:index' %}">CLIENTES</a>
</header>

<main id="container-principal">
    <div id="img-container-form"><img src="{% static 'logo.svg' %}"></div> 

    <h1>Entrar</h1>

    <form method="post" action="{% url 'accounts:equipe_login' %}">
        {% csrf_token %}
        <input type="input" class="form-control" name="username" id="inputUser" placeholder="Nome" required >
        <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Senha" required>

        <br>

        {% if form.errors %}
            {% for field in form.errors %}
                {% for error in form.errors|get_item:field %}
                    <p class="errortext">{{ error }}</p>
                {% endfor %}
            {% endfor %}
        {% endif %}

        {% if next %}
        {% if user.is_authenticated %}
        <p class="errortext">Sua conta não possui acesso a esta página. Para prosseguir, faça um login com uma conta que tenha.</p>
        {% else %}
        <p class="errortext">Faça o login para ver esta página.</p>
        {% endif %}
        {% endif %}

        <button id="button" type="submit" value="login">Entrar</button>
        <input type="hidden" name="next" value="{{ next }}">
    </form>
</main>

{% endblock content %}